CREATE DATABASE escola;
USE escola;
CREATE TABLE aluno(
 idAluno INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 nomeAluno VARCHAR(150) NOT NULL,
 email VARCHAR(150) NOT NULL,
 curso VARCHAR(100) NOT NULL,
 mediaFinal DECIMAL(5,2) NOT NULL,
 dataCadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
 );
 
 CREATE TABLE professor(
 idAluno INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 nomeProfessor VARCHAR(150) NOT NULL,
 disciplina VARCHAR(100) NOT NULL,
 cargaHoraria INT NOT NULL,
 dataCadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
 );
 
 CREATE TABLE disciplina (
 id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 nomeDisciplina VARCHAR (100) NOT NULL
 )
 